import Head from "next/head";

import { NextPage } from "next/types";
import Header from "./Header";

interface Props {
  children: React.ReactNode;
  title: string | string[];
}

const MainLayout: NextPage<Props> = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Header />
      <main>{children}</main>
      <footer>подвад</footer>
    </>
  );
};

export default MainLayout;
